AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    props

    Sample SAM Template for props

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Function:
        Timeout: 20


Resources:

    PropsFunction:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            CodeUri: target/props-1.0-SNAPSHOT.jar
            Handler: example.props.Props::handleRequest
            Runtime: java8
            Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
                Variables:
                    PARAM1: VALUE

Outputs:

    PropsFunction:
      Description: "Props Lambda Function ARN"
      Value: !GetAtt PropsFunction.Arn

    PropsFunctionIamRole:
      Description: "Implicit IAM Role created for Hello World function"
      Value: !GetAtt PropsFunctionRole.Arn
